apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: docker-registries-mirror
  labels:
    app: docker-registries-mirror
spec:
  hostNetwork: true
  containers:
  - name: docker-registries-mirror
    image: mcluseau/docker-registries-mirror
    args:
    - -addr=:8585
    - -cache-mib=20000
    - -peers=http://192.168.1.2:8585,http://192.168.1.3:8585
    # example proxy configuration:
    #env:
    #- name: HTTP_PROXY
    #  value: http://proxy.org.local:3128
    #- name: HTTPS_PROXY
    #  value: http://proxy.org.local:3128
    volumeMounts:
    - name: cache
      mountPath: "/cache"
  volumes:
  - name: cache
    hostPath:
      path: /var/lib/containerd/cache
